/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iFP.pr_daw_p4_puentes_arturo;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author ajpyu
 */
public class PanelAlta extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlta
     */
    public PanelAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ClasesAnimales = new javax.swing.JScrollPane();
        jListClases = new javax.swing.JList<>();
        jLabelEspecie = new javax.swing.JLabel();
        Especie = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        Peso = new javax.swing.JTextField();
        jLabelLesion = new javax.swing.JLabel();
        Lesion = new javax.swing.JTextField();
        jLabelGravedad = new javax.swing.JLabel();
        jScrollPaneGravedad = new javax.swing.JScrollPane();
        jListGravedad = new javax.swing.JList<>();
        jLabelVet = new javax.swing.JLabel();
        Veterinario = new javax.swing.JComboBox<>();
        jLabelFecha = new javax.swing.JLabel();
        FechaDeAlta = new javax.swing.JTextField();
        DatoExtra = new javax.swing.JRadioButton();
        DarAlta = new javax.swing.JButton();

        setBackground(new java.awt.Color(246, 251, 244));
        setMaximumSize(new java.awt.Dimension(260, 556));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(75, 134, 115));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Alta");
        Titulo.setToolTipText("");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Clase Animal:");

        jListClases.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ave", "Mamífero", "Reptil" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClasesMouseClicked(evt);
            }
        });
        ClasesAnimales.setViewportView(jListClases);

        jLabelEspecie.setText("Especie:");

        Especie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EspecieKeyTyped(evt);
            }
        });

        jLabelPeso.setText("Peso:");

        Peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PesoKeyTyped(evt);
            }
        });

        jLabelLesion.setText("Lesion:");

        Lesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LesionKeyTyped(evt);
            }
        });

        jLabelGravedad.setText("Gravedad:");

        jListGravedad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Baja", "Media", "Urgente" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneGravedad.setViewportView(jListGravedad);

        jLabelVet.setText("Veterinario:");

        Veterinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juan", "Roberto", "Carlos" }));

        jLabelFecha.setText("Fecha:");

        DatoExtra.setText("Selecciona una clase de animal");

        DarAlta.setBackground(new java.awt.Color(245, 223, 153));
        DarAlta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DarAlta.setForeground(new java.awt.Color(75, 134, 115));
        DarAlta.setText("Dar Alta");
        DarAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(DarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelGravedad)
                            .addComponent(jScrollPaneGravedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(ClasesAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Veterinario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(DatoExtra))
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelLesion)
                                .addComponent(jLabelPeso)
                                .addComponent(jLabelEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Especie)
                                .addComponent(Peso)
                                .addComponent(FechaDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(Lesion)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Especie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelVet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClasesAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGravedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneGravedad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DatoExtra)
                .addGap(18, 18, 18)
                .addComponent(DarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Especie.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void EspecieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EspecieKeyTyped
        IntroLetras(evt);
    }//GEN-LAST:event_EspecieKeyTyped

    private void LesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LesionKeyTyped
        IntroLetras(evt);
    }//GEN-LAST:event_LesionKeyTyped

    private void PesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesoKeyTyped
        IntroNumeros(evt);
    }//GEN-LAST:event_PesoKeyTyped

    private void jListClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClasesMouseClicked
        if (jListClases.getSelectedIndex() == 0 ) {
            DatoExtra.setText("Caza Furtiba");
        }
        if (jListClases.getSelectedIndex() == 1 ) {
            DatoExtra.setText("Atropellado");
        }
        if (jListClases.getSelectedIndex() == 2 ) {
            DatoExtra.setText("Infercción bacteriana");
        }
    }//GEN-LAST:event_jListClasesMouseClicked

    private void DarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarAltaActionPerformed
        if (jListClases.getSelectedIndex() == 0 ) {
            Ave e = new Ave(DatoExtra.isSelected(),Especie.getText(),Integer.parseInt(Peso.getText()),Lesion.getText(),jListGravedad.getSelectedValue(),String.valueOf(Veterinario.getSelectedItem()),FechaDeAlta.getText(),"",false);
            Principal.addListado(e);
        }
        if (jListClases.getSelectedIndex() == 1 ) {
            Mamifero e = new Mamifero(DatoExtra.isSelected(),Especie.getText(),Integer.parseInt(Peso.getText()),Lesion.getText(),jListGravedad.getSelectedValue(),String.valueOf(Veterinario.getSelectedItem()),FechaDeAlta.getText(),"",false);
            Principal.addListado(e);
        }
        if (jListClases.getSelectedIndex() == 2 ) {
            Reptil e = new Reptil(DatoExtra.isSelected(),Especie.getText(),Integer.parseInt(Peso.getText()),Lesion.getText(),jListGravedad.getSelectedValue(),String.valueOf(Veterinario.getSelectedItem()),FechaDeAlta.getText(),"",false);
            Principal.addListado(e);
        }
    }//GEN-LAST:event_DarAltaActionPerformed

    private static void IntroLetras(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)) {
            evt.consume();
        }
    }
    
    private static void IntroNumeros(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    public void InitFecha(){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date();   
        FechaDeAlta.setText(formato.format(date));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ClasesAnimales;
    private javax.swing.JButton DarAlta;
    private javax.swing.JRadioButton DatoExtra;
    private javax.swing.JTextField Especie;
    private javax.swing.JTextField FechaDeAlta;
    private javax.swing.JTextField Lesion;
    private javax.swing.JTextField Peso;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> Veterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEspecie;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGravedad;
    private javax.swing.JLabel jLabelLesion;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelVet;
    private javax.swing.JList<String> jListClases;
    private javax.swing.JList<String> jListGravedad;
    private javax.swing.JScrollPane jScrollPaneGravedad;
    // End of variables declaration//GEN-END:variables
}
